---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Ensure Nginx is running and enabled
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Create Nginx configuration directory for conf.d
  file:
    path: /etc/nginx/conf.d
    state: directory
    mode: '0755'

- name: Create Nginx configuration for EpicBook in conf.d
  template:
    src: theepicbooks.conf.j2
    dest: /etc/nginx/conf.d/theepicbooks.conf
    backup: yes
  notify: Reload Nginx

- name: Test Nginx configuration
  command: nginx -t
  register: nginx_test
  changed_when: false

- name: Show Nginx test result
  debug:
    msg: "{{ nginx_test.stdout }}"

- name: Ensure firewall allows HTTP traffic
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Reload firewall
  ufw:
    state: reloaded