#cloud-config
package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - git
  - unzip
  - build-essential
  - python3-pip
  - mysql-client

runcmd:
  - |
    # Install Node.js 18.x
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
    apt-get install -y nodejs
  - |
    # Create application directory
    mkdir -p /var/www/epicbook
    chown azureuser:azureuser /var/www/epicbook
  - |
    # Clone the repository
    cd /tmp
    git clone https://github.com/pravinmishraaws/theepicbook.git
    cp -r theepicbook/* /var/www/epicbook/
    chown -R azureuser:azureuser /var/www/epicbook
  - |
    # Install Nginx
    apt-get install -y nginx
    systemctl enable nginx
  - |
    # Create Nginx config
    cat > /etc/nginx/sites-available/epicbook << 'EOF'
    server {
        listen 80;
        server_name _;
        
        location / {
            proxy_pass http://localhost:8080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;
        }
    }
    EOF

    ln -sf /etc/nginx/sites-available/epicbook /etc/nginx/sites-enabled/
    rm -f /etc/nginx/sites-enabled/default
    nginx -t && systemctl restart nginx
  - |
    # Install app dependencies
    cd /var/www/epicbook
    sudo -u azureuser npm install